### ISSUE TITLE
update EXiST mysqldb

### ISSUE THREAD

**Issue by tRyzoNeT** [tRyzoNeT/bonaPRE-public#5]
Est-ce qu'il y a un moyen pour UPDATE certaines information dans la database mysql plus rapidement que de vérifier si le ROW exist avant d'update... Avec une grosse db, sa ping timeout le 3/4 avant même de vérifier

```
set sql "SELECT * FROM `${dbsql}` WHERE nick = `${nick}`";
set sqld [::mysql::sel ${mysql_(handle)} ${sql}];
if { ${AI_Sqld} == "1" } {
 UPDATE DB
} else { UPDATE RiEN, ROW PAS EXiSTANT }
```

@ZarTek-Creole idée suggestion??

**Comment by ZarTek-Creole** [comment]
@tRyzoNeT : De ce que je comprends, plusieurs points peuvent être abordés car différents facteurs pourraient expliquer le problème. La première chose à vérifier serait si un index est correctement défini sur votre table. Pour cela, le résultat de "**EXPLAIN** SELECT * FROM `${dbsql}` WHERE nick = `${nick}`" pourrait nous informer si un index est utilisé ou s'il est nécessaire de faire une recherche complète (full search), ce qui pourrait expliquer le souci. 

En deuxième point, si vous voulez éviter de faire un SELECT avant chaque UPDATE, vous pourriez envisager d'utiliser cette commande : 

```sql
INSERT INTO `${dbsql}` (nick, column1, column2)
VALUES ('${nick}', '${value1}', '${value2}')
ON DUPLICATE KEY UPDATE column1 = '${value1}', column2 = '${value2}';
```

Cette commande mettra à jour l'enregistrement si celui-ci existe, ou l'insérera s'il est manquant. Cela devrait rendre votre opération plus efficace.

**Comment by tRyzoNeT** [comment]
j'aime bien le 2ieme point sa evite de select... sauf que je ne desire pas insert s'il n'est pas present, je veut juste update s'il y a. Comment procede dans ce cas

**Comment by ZarTek-Creole** [comment]
C'est ce que je pensais avoir compris. Alors pour aller vers la deuxième solution tu peux faire un UPDTAE tout simplement, car si il ne trouve pas de valeur par rapport a ta clause WHERE il ne fera rien ca t'évite de faire deux requête. Ca donnerais simplement quelque chose comme ceci:

```
UPDATE `${dbsql}`
SET column1 = '${value1}', column2 = '${value2}'
WHERE nick = '${nick}';

```
Cependant, l'autre point que je metais en avant pour améliorer les performances, je terecommanderais toujours de vous assurer que tu avez correctement indexé la colonne utilisée dans votre clause WHERE (nick dans cet exemple). Un bon index peut grandement améliorer les performances de vos requêtes SELECT, UPDATE et DELETE.

Pour le savoir je me recite avec l exemple de "EXPLAIN"

`EXPLAIN SELECT * FROM ${dbsql} WHERE nick = ${nick}`

Qui donnera comme résultat comment sql aborde ta requête SQL et si il utilise bien un INDEX

Si ton serveur SQL tourne depuis un moment donnée genre un mois, tu pourais voir avec mysqltuner pour ameliorer les configurations global a sql. comme la mémoire aloué pour des tables TMP et autres. l'activation temporaire du slow query pourais aussi determiné tes requette lente pour amelioré

**Comment by tRyzoNeT** [comment]
thank du coup de main buddy...

je vais m'instruire sur EXPLAIN 👍

**Comment by tRyzoNeT** [comment]
thank du coup de main buddy...

je vais m'instruire sur EXPLAIN 👍
